// The 130 current NSW local government areas, hand-typed once from the
// public "List of local government areas in New South Wales" reference
// (cross-checked against the NSW Office of Local Government's council
// count of 128 gazetted councils — this list also includes the two
// LGA-equivalent unincorporated areas, Lord Howe Island and Unincorporated
// Far West). Real, sourced, bounded — same convention as every other
// hand-typed reference list in this repo, not a scraped or guessed set.
export const NSW_LGAS: string[] = [
  "City of Albury",
  "Armidale Regional Council",
  "Ballina Shire",
  "Balranald Shire",
  "Bathurst Region",
  "Bayside Council",
  "Bega Valley Shire",
  "Bellingen Shire",
  "Berrigan Shire",
  "Blacktown City Council",
  "Bland Shire",
  "Blayney Shire",
  "City of Blue Mountains",
  "Bogan Shire",
  "Bourke Shire",
  "Brewarrina Shire",
  "City of Broken Hill",
  "Burwood Council",
  "Byron Shire",
  "Cabonne Shire",
  "Camden Council",
  "City of Campbelltown",
  "City of Canada Bay",
  "City of Canterbury-Bankstown",
  "Carrathool Shire",
  "Central Coast Council",
  "Central Darling Shire",
  "City of Cessnock",
  "Clarence Valley Council",
  "Cobar Shire",
  "City of Coffs Harbour",
  "Coolamon Shire",
  "Coonamble Shire",
  "Cootamundra-Gundagai Regional Council",
  "Cowra Shire",
  "Cumberland City Council",
  "Dubbo Regional Council",
  "Dungog Shire",
  "Edward River Council",
  "Eurobodalla Shire",
  "City of Fairfield",
  "Federation Council",
  "Forbes Shire",
  "Georges River Council",
  "Gilgandra Shire",
  "Glen Innes Severn Council",
  "Goulburn Mulwaree Council",
  "Greater Hume Shire",
  "City of Griffith",
  "Gunnedah Shire",
  "Gwydir Shire",
  "City of Hawkesbury",
  "Hay Shire",
  "The Hills Shire",
  "Hilltops Council",
  "Hornsby Shire",
  "Municipality of Hunter's Hill",
  "Inner West Council",
  "Inverell Shire",
  "Junee Shire",
  "Kempsey Shire",
  "Municipality of Kiama",
  "Ku-ring-gai Council",
  "Kyogle Council",
  "Lachlan Shire",
  "City of Lake Macquarie",
  "Municipality of Lane Cove",
  "Leeton Shire",
  "City of Lismore",
  "City of Lithgow",
  "City of Liverpool",
  "Liverpool Plains Shire",
  "Lockhart Shire",
  "Lord Howe Island",
  "City of Maitland",
  "Mid-Coast Council",
  "Mid-Western Regional Council",
  "Moree Plains Shire",
  "Mosman Council",
  "Murray River Council",
  "Murrumbidgee Council",
  "Muswellbrook Shire",
  "Nambucca Shire",
  "Narrandera Shire",
  "Narrabri Shire",
  "Narromine Shire",
  "City of Newcastle",
  "Northern Beaches Council",
  "North Sydney Council",
  "Oberon Shire",
  "City of Orange",
  "Parkes Shire",
  "City of Parramatta Council",
  "City of Penrith",
  "Port Macquarie-Hastings Council",
  "Port Stephens Council",
  "Queanbeyan–Palerang Regional Council",
  "City of Randwick",
  "Richmond Valley Council",
  "City of Ryde",
  "Singleton Council",
  "City of Shellharbour",
  "City of Shoalhaven",
  "Snowy Monaro Regional Council",
  "Snowy Valleys Council",
  "Municipality of Strathfield",
  "Sutherland Shire",
  "City of Sydney",
  "Tamworth Regional Council",
  "Temora Shire",
  "Tenterfield Shire",
  "Tweed Shire",
  "Unincorporated Far West",
  "Upper Hunter Shire",
  "Upper Lachlan Shire",
  "Uralla Shire",
  "City of Wagga Wagga",
  "Walcha Shire",
  "Walgett Shire",
  "Warren Shire",
  "Warrumbungle Shire",
  "Waverley Council",
  "Weddin Shire",
  "Wentworth Shire",
  "City of Willoughby",
  "Wingecarribee Shire",
  "Wollondilly Shire",
  "City of Wollongong",
  "Municipality of Woollahra",
  "Yass Valley Council",
];

// Canonical matching key for an LGA name — strips common prefixes/suffixes
// that vary between how a council styles itself, how Nominatim reports
// `address.municipality`/`county`, and how a source adapter tags its own
// records, so all three land on the same string. Heuristic, not perfect —
// if Nominatim's real-world output for NSW addresses turns out to diverge
// meaningfully once this is used against live geocoding (Phase 2), that's
// the trigger to replace this with a proper ABS SAL→LGA correspondence
// table rather than growing this regex further.
export function normalizeLgaName(raw: string): string {
  return raw
    .replace(/^(City of|Municipality of)\s+/i, "")
    .replace(/\s+(City|Regional|Shire|County)?\s*Council$/i, "")
    .trim()
    .toUpperCase();
}

export const NORMALIZED_NSW_LGAS: { display: string; key: string }[] = NSW_LGAS.map((display) => ({
  display,
  key: normalizeLgaName(display),
}));
