import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { AmbientSection } from "@/components/ambient/AmbientSection";
import { SlideIn } from "@/components/motion/ScrollAnimations";

export const metadata = {
  title: "Glossary - REITCompare",
  description: "Learn the terminology used in Australian Real Estate Investment Trusts.",
};

const terms = [
  {
    term: "WALE (Weighted Average Lease Expiry)",
    definition: "A metric used to measure the average time period that all leases in a property portfolio will expire, weighted by the rental income of each lease. A higher WALE indicates longer-term income security."
  },
  {
    term: "NTA (Net Tangible Assets)",
    definition: "The total assets of a REIT minus its liabilities and intangible assets. Often expressed as NTA per security. When a REIT's unit price is below its NTA, it is trading at a discount."
  },
  {
    term: "Gearing",
    definition: "A measure of a REIT's financial leverage, usually calculated as total debt divided by total assets. Lower gearing generally means lower financial risk."
  },
  {
    term: "Distribution Yield",
    definition: "The income return on an investment. For REITs, it is calculated by dividing the annual distribution per security by the current security price."
  },
  {
    term: "Capitalisation Rate (Cap Rate)",
    definition: "The rate of return on a real estate investment property based on the income that the property is expected to generate."
  },
  {
    term: "Funds From Operations (FFO)",
    definition: "A measure of the cash generated by a REIT from its operations. It adds depreciation and amortization back to earnings and subtracts gains on sales."
  }
];

export default function GlossaryPage() {
  return (
    <div className="flex min-h-screen flex-col bg-[#F7F8FA]">
      <SiteHeader />
      <main className="flex-1">
        <section className="py-20 md:py-32 bg-transparent relative overflow-hidden min-h-[80vh]">
          <AmbientSection theme="neutral" />
          <div className="mx-auto max-w-4xl px-6 sm:px-8 relative z-10">
            <SlideIn direction="up">
              <h1 className="font-display text-4xl md:text-5xl font-bold tracking-tight text-foreground mb-4">Glossary</h1>
              <p className="text-lg text-muted-foreground mb-16">
                Understand the key terms and metrics used in Australian property-backed investing.
              </p>
            </SlideIn>
            
            <div className="space-y-8">
              {terms.map((item, index) => (
                <SlideIn key={item.term} direction="up" delay={index * 0.05}>
                  <div className="bg-white rounded-lg shadow-[0_8px_30px_rgba(23,32,42,0.04)] border border-border/60 p-6 md:p-8">
                    <h3 className="text-xl font-bold text-foreground mb-3">{item.term}</h3>
                    <p className="text-muted-foreground leading-relaxed">{item.definition}</p>
                  </div>
                </SlideIn>
              ))}
            </div>
          </div>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
